<%
WANT_AUTHNET =1
WANT_CID_MANDATORY =1
WANT_ECHECK =1
WANT_PAYPAL =1
PAYPAL_HOLD_DAYS =15
AUTHNET_ERR_NOTIFY =""
WANT_GOOGLECHECKOUT =0
ALLOW_POINTS =0
ALLOW_GC =1
ALLOW_GCARD =0
WANT_PAYPALEXPRESS =0
WANT_BILLMELATER =0
%>
