<%
PRODUCTS_PER_PAGE =50
SHOW_PRODUCTSLISTVIEW =0
PRODUCTS_PER_GRID=3
PROD_IMAGE_WIDTH =0
PROD_IMAGE_HEIGHT =0
SHOW_IN_STOCK =1
SHOW_DUE_DATE =1
SHOW_COMP_PRICE ="TRUE"
SHOW_QTY =1
SHOW_PRODUCTREVIEWS =1
SHOW_RECENTLYVIEWEDPRODUCTS =1
SHOW_MINMAXPRICE =1
SHOW_PRODSHIPCHRG =0
SHOW_BESTSELLER =0
BEST_SELLERS_COUNT =5
%>
