<%
ALT_HOME_TXT ="Home"
ALT_ABOUT_TXT ="About Us"
ALT_CONTACT_TXT ="Contact Us"
ALT_FAQ_TXT ="Faq"
ALT_PRIVACY_TXT ="Privacy Policy"
ALT_TESTIMONIAL_TXT ="Testimonials"
ALT_HELP_TXT ="Shipping Policy"
ALT_RETURN_TXT ="Meet the Staff"
ALT_TERMS_TXT ="Size Charts"

DISP_ABOUT_PAGE =True
DISP_CONTACT_PAGE =True
DISP_FAQ_PAGE =True
DISP_PRIVACY_PAGE =True
DISP_TESTIMONIAL_PAGE =True
DISP_HELP_PAGE =True
DISP_RETURN_PAGE =True
DISP_TERMS_PAGE =True
%>
